FROM golang:1.19 as builder

ENV CGO_ENABLED=0

WORKDIR /build

COPY . .

RUN make dist


FROM alpine:3.16

WORKDIR /app

COPY --from=builder /build/dist/ .

# This is for demonstration purposes only. NEVER include your keys in your GitHub repo,
# use GitHub secrets instead.
COPY keys .

ENTRYPOINT ["/app/secure-store", "-server"]
